language: node_js
node_js:
  - "12.19.0"

sudo: required

# Supposedly this is needed for Cypress to work in Ubuntu 16
# https://github.com/cypress-io/cypress-example-kitchensink/blob/master/basic/.travis.yml
addons:
  apt:
    packages:
      - libgconf-2-4

env:
  global:
    - DOCKER_COMPOSE_VERSION: 1.24.1

services:
  - docker

before_install:
  - docker-compose up --build -d
  - docker ps -a

script:
  # Run unit tests
  - cd next
  - npm run test
  # Run e2e tests
  - cd ../e2e
  - npx cypress verify
  - npx cypress run -- --record

post_script:
  - docker-compose stop
